services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev  # Development-specific environment variables

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    env_file:
      - .env.dev  # Development-specific environment variables
    volumes:
      - ./frontend:/app  # Mount frontend code for hot reloading
      - /app/node_modules  # Exclude node_modules from host

  celery:
    container_name: x_tracker_celery
    extends:
      file: docker-compose.yml
      service: backend
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev
    restart: unless-stopped

  celery-beat:
    container_name: x_tracker_celery_beat
    extends:
      file: docker-compose.yml
      service: backend
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - redis
    env_file:
      - .env.dev
    restart: unless-stopped