version: '3.8'

services:
  db:
    image: postgres:13
    container_name: x_tracker_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env 
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    container_name: x_tracker_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: x_tracker_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Use .env for development settings
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build: ./backend
    container_name: x_tracker_celery_worker
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A config worker -l INFO

  celery_beat:
    build: ./backend
    container_name: x_tracker_celery_beat
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery_worker
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  frontend:
    build: ./frontend
    container_name: x_tracker_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:8000  # Use the service name
    depends_on:
      - backend

volumes:
  postgres_data:
